wasimoff: cmd/wasimoff/main.go
	go build -o $@ $<

gcp_invoke: cmd/gcp_invoke/main.go
	go build -o $@ $<

tspbench: cmd/tspbench/main.go
	go build -o $@ $<

tracebench: cmd/tracebench/main.go
	go build -o $@ ./cmd/tracebench/
