#!/usr/bin/env bash
set -eu

# get a current auth token
TOKEN=$(gcloud auth print-identity-token)

# get the function endpoint
URL=$(gcloud run services describe wasip1-runner --format json | jq -r .status.url)

# use this binary url for tsp.wasm
wasm="https://wasi.team/api/storage/tsp.wasm"

# post the offloading request
curl -f -X POST "$URL" \
  -H "Authorization: bearer $TOKEN" \
  -H "Content-Type: application/json" \
  --data-raw "$(jq -n --arg wasm "$wasm" --args \
    '{ "binary": $wasm, "argv": [ "tsp.wasm", $ARGS.positional[] ] }' "$@" \
  )"
exit $?
