services:

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

  createbuckets:
    image: quay.io/minio/minio
    container_name: minio-createbuckets
    depends_on: [ minio ]
    entrypoint: >
      /bin/bash -c "
      until curl -s http://minio:9000/minio/health/ready; do echo .; sleep 1; done;
      mc alias set minio http://minio:9000 admin password;
      mc mb minio/wasimoff;
      mc anonymous set download minio/wasimoff;
      exit 0;
      "
