{
 "title": "Wasimoff2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "wasimoff_available_workers{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Connected Providers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "wasimoff_connected_providers{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Throughput (ok)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(wasimoff_tasks_completed_count{instance=\"$instance\", status=\"ok\", target=\"provider\"}[$__rate_interval])",
     "legendFormat": "wasimoff_completed_tasks ({{ target }})"
    },
    {
     "expr": "rate(wasimoff_tasks_completed_count{instance=\"$instance\", status=\"ok\", target=\"cloud\"}[$__rate_interval])",
     "legendFormat": "wasimoff_completed_tasks ({{ target }})"
    }
   ]
  },
  {
   "title": "Tasks in Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "wasimoff_tasks_queued{instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "wasimoff_tasks_dispatching{instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Throughput (Provider)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(wasimoff_tasks_completed_count{instance=\"$instance\", status=\"ok\", target=\"provider\"}[$__rate_interval])",
     "legendFormat": "wasimoff_completed_tasks ({{ target }})"
    }
   ]
  },
  {
   "title": "Throughput (Cloud)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(wasimoff_tasks_completed_count{instance=\"$instance\", status=\"ok\", target=\"cloud\"}[$__rate_interval])",
     "legendFormat": "wasimoff_completed_tasks ({{ target }})"
    }
   ]
  },
  {
   "title": "Task Successful Execution Time Heatmap",
   "type": "heatmap",
   "description": "Pure computation time after scheduling.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (increase(wasimoff_tasks_execution_bucket{instance=\"$instance\", status=\"ok\"}[$__rate_interval]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Task Execution Time",
   "type": "bargauge",
   "description": "Within the current view range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(wasimoff_tasks_execution_bucket{instance=\"$instance\"}[$__range]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Task Completion Time Heatmap",
   "type": "heatmap",
   "description": "Full task lifetime from request to finished result.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(le) (increase(wasimoff_tasks_completed_bucket{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Task Completion Time",
   "type": "bargauge",
   "description": "Within the current view range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(wasimoff_tasks_completed_bucket{instance=\"$instance\"}[$__range]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(wasimoff_task_retries_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ attempt }}. try"
    }
   ]
  },
  { "title": "Go Runtime internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Threads and Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "go_sched_gomaxprocs_threads{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "go_threads{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "gc_duration q={{ quantile }}"
    }
   ]
  }
 ]
}